### ISSUE TITLE
Running sudo ln -s $(pwd)/amdgpu-clocks /usr/local/bin/amdgpu-clocks Creates a broken link

### ISSUE THREAD

**Issue by justbest23** [sibradzic/amdgpu-clocks#36]
Thank you for making this. I'm sure it's something I'm doing wrong on my end but I can't figure it out. I run the command above (`sudo ln -s $(pwd)/amdgpu-clocks /usr/local/bin/amdgpu-clocks`) and it creates a broken link that I cannot access. When I try to manually copy the script into a file of the same name in the same dir I get `Unexpected error: Error opening file “/usr/local/bin/amdgpu-clocks”: Too many levels of symbolic links`.

Any help would be greatly appreciated!

**Comment by sibradzic** [comment]
ping

**Comment by justbest23** [comment]
Huge apologies for not getting back to you. I ended up rolling back the kernel version and it all worked out fine. Thank you.
