### ISSUE TITLE
*feature request* Adjust Power Cap Limit

### ISSUE THREAD

**Issue by MilesRdz** [sibradzic/amdgpu-clocks#4]
Would it be possible to include the option to increase the amount of power the GPU is allowed to use?
/sys/class/drm/cardX/device/hwmon/hwmon0/power1_cap

**Comment by sibradzic** [comment]
Sure thing. Since I'm gonna be away from desktop PC with any Radeons inside, can you please point me to an example how `powerX_cap` is being set in terminal? I also assume you'd volunteer as a tester? ;)

**Comment by sibradzic** [comment]
@MilesRdz please check if this adds the requested feature correctly...

**Comment by MilesRdz** [comment]
> @MilesRdz please check if this adds the requested feature correctly...

It works as intended, thank you!
