### ISSUE TITLE
FORCE_MCLK stops working when VRAM is overclocked

### ISSUE THREAD

**Issue by forte97** [sibradzic/amdgpu-clocks#43]
I'm running mint 20.3 with an RX 470. when I go above my stock clock of 1750MHz for RAM, FORCE_MCLK stops working on reboot/login. Running sudo amdgpu-clocks again doesn't solve it either, since(I think) it doesn't change anything if the custom states file isn't modified.

Update: when I disable FORCE_MCLK and set FORCE_PERF_LEVEL to high, the changes do persist after reboot.

**Comment by sibradzic** [comment]
Must be yet another driver or SMU quirk, not much I can do about it.
